#!/bin/sh
cd "$HOME" || { echo 'Changing into home directory failed' >&2 ; exit 1 ;}

# Init git submodules
echo 'Init submodules'
yadm submodule update --recursive --init

# Install mpv scripts
mkdir ~/.config/mpv
mkdir ~/.config/mpv/scripts
mkdir ~/.config/mpv/script-modules
echo 'Installing mpv scripts'
curl --output-dir ~/.config/mpv/scripts 'https://raw.githubusercontent.com/kism/mpvscripts/main/scripts/vlcaspectratio.lua'
curl --output-dir ~/.config/mpv/scripts 'https://raw.githubusercontent.com/kism/mpvscripts/main/scripts/vlccrop.lua'
curl --output-dir ~/.config/mpv/scripts 'https://raw.githubusercontent.com/mpv-player/mpv/master/TOOLS/lua/acompressor.lua'
curl --output-dir ~/.config/mpv/scripts 'https://raw.githubusercontent.com/mpv-player/mpv/master/TOOLS/lua/autocrop.lua'
curl --output-dir ~/.config/mpv/scripts 'https://raw.githubusercontent.com/CogentRedTester/mpv-coverart/master/coverart.conf'
curl --output-dir ~/.config/mpv/scripts 'https://gist.githubusercontent.com/ntasos/d1d846abd7d25e4e83a78d22ee067a22/raw/kdialog-open-files.lua'
curl --output-dir ~/.config/mpv/scripts 'https://gist.githubusercontent.com/avih/41acff712abd32e1f436235388c8b523/raw/equalizer.lua'
curl --output-dir ~/.config/mpv/scripts 'https://raw.githubusercontent.com/jonniek/mpv-menu/master/menu.lua'
curl --output-dir ~/.config/mpv/scripts 'https://raw.githubusercontent.com/jonniek/mpv-playlistmanager/master/playlistmanager.lua'
curl --output-dir ~/.config/mpv/scripts 'https://raw.githubusercontent.com/zc62/mpv-scripts/master/screenshot-to-clipboard.js'
curl --output-dir ~/.config/mpv/script-modules 'https://raw.githubusercontent.com/CogentRedTester/mpv-scroll-list/master/scroll-list.lua'
curl --output-dir ~/.config/mpv/script-modules 'https://raw.githubusercontent.com/CogentRedTester/mpv-user-input/master/user-input-module.lua'
curl --output-dir ~/.config/mpv/scripts 'https://raw.githubusercontent.com/CogentRedTester/mpv-search-page/master/search-page.lua'
